### ISSUE TITLE
Changing from 0.1.3 to 0.1.4 breaks code sniffer.

### ISSUE THREAD

**Issue by mzstic** [Symplify/CodingStandard#6]
After updating symplify/coding-standard version CS stopped working.

`MethodCommentReturnTagSniff` was renamed to `MethodReturnTypeSniff`.
When using custom ruleset, CS starts throwing error. Within one major version sniffs shouldn't be renamed as it causes bc break.

**Comment by TomasVotruba** [comment]
Since 0.* is dev version, semantic versioning is not applied in matters of BC compatibility. 


See point 4: http://semver.org/

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I'd recommend using 0.1.3 if you don't need new features and this causes you issues.

Saying that, do you use sniffs somehow manually?
